name: 'Universal Dependabot Manager'
description: 'A custom GitHub Action to enable vulnerability alerts, fetch security alerts, and create pull requests for security vulnerabilities in repositories.'
author: 'Pulak Paul'
inputs:
  github_token:
    description: 'GitHub token with repository access'
    required: true
outputs:
  alerts_processed:
    description: 'The number of security alerts processed.'
branding:
  color: 'blue'
  icon: 'shield'
runs:
  using: 'node16'
  main: 'dist/index.js'